# Generated by Django 3.2.4 on 2021-07-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('Action', 'Action'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('History', 'History'), ('Literary', 'Literary'), ('Biography', 'Biography')], max_length=200)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic'), ('French', 'French'), ('Persian', 'Persian'), ('Sanskrit', 'Sanskrit')], max_length=200)),
            ],
        ),
    ]
